apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: nginx
          image: misha1607/os2:v2
          ports:
            - containerPort: 80


